# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: 2dust.v2rayN
PackageVersion: 7.25.4
InstallerType: zip
NestedInstallerType: portable
Installers:
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: v2rayN-windows-arm64\v2rayN.exe
  InstallerUrl: https://github.com/2dust/v2rayN/releases/download/7.25.4/v2rayN-windows-arm64.zip
  InstallerSha256: 2253DEDDCD88DD93641EE6B2CA5DE6FF8B9062867B656B29DBD13D214BC2CDAD
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: v2rayN-windows-64\v2rayN.exe
  InstallerUrl: https://github.com/2dust/v2rayN/releases/download/7.25.4/v2rayN-windows-64.zip
  InstallerSha256: E699DDC7F02D060DEE2B0005D3879D82DB1C36961B866D1ED0F9F93F16390A6B
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
